CREATE DATABASE IF NOT EXISTS juniortest;
USE juniortest;


CREATE TABLE IF NOT EXISTS books (
    id INT PRIMARY KEY AUTO_INCREMENT,
    sku VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(30) NOT NULL,
    price INT NOT NULL,
    weight INT NOT NULL
);

CREATE TABLE IF NOT EXISTS dvds (
    id INT PRIMARY KEY AUTO_INCREMENT,
    sku VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(30) NOT NULL,
    price INT NOT NULL,
    size INT NOT NULL
);

CREATE TABLE IF NOT EXISTS furniture (
    id INT PRIMARY KEY AUTO_INCREMENT,
    sku VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    dimensions VARCHAR(255) NOT NULL
);